import type { Kind } from './types'

export const TOPIC_SUFFIX = ' - Topic'

export function isTopicChannel(channel: string | undefined): boolean {
  return !!channel && channel.endsWith(TOPIC_SUFFIX)
}

export function isAutoGeneratedDescription(description: string | undefined): boolean {
  if (!description) return false
  return description.trimStart().startsWith('Provided to YouTube by') && description.includes('Auto-generated by YouTube')
}

export function classify(channel: string | undefined, description: string | undefined): Kind {
  return isTopicChannel(channel) || isAutoGeneratedDescription(description) ? 'track' : 'music'
}

export function stripTopic(channel: string): string {
  return isTopicChannel(channel) ? channel.slice(0, -TOPIC_SUFFIX.length) : channel
}
