import { stripTopic } from './classify'

export const SEPARATOR = ' · '

export interface TrackMeta {
  artist: string
  album: string
}

const NOT_ALBUM = /^(℗|©|Released on:|Auto-generated by YouTube|Provided to YouTube by)/

function artistFromLine(line: string, title: string): string | null {
  const prefix = title + SEPARATOR
  const rest = title && line.startsWith(prefix) ? line.slice(prefix.length) : line.split(SEPARATOR).slice(1).join(SEPARATOR)
  const artist = rest.split(SEPARATOR)[0]?.trim()
  return artist ? artist : null
}

export function parseTrackDescription(description: string, title: string, channel: string): TrackMeta {
  const lines = description.split(/\r?\n/).map(l => l.trim())
  const index = lines.findIndex(l => l.includes(SEPARATOR) && !NOT_ALBUM.test(l))
  let artist: string | null = null
  let album = ''
  if (index >= 0) {
    artist = artistFromLine(lines[index]!, title)
    const next = lines.slice(index + 1).find(l => l.length > 0)
    if (next && !NOT_ALBUM.test(next)) album = next
  }
  return { artist: artist ?? stripTopic(channel), album }
}
