import { stripTopic } from './classify'

export const SEPARATOR = ' · '

export interface TrackMeta {
  artists: string[]
  album: string
}

const NOT_ALBUM = /^(℗|©|Released on:|Auto-generated by YouTube|Provided to YouTube by)/

function artistsFromLine(line: string, title: string): string[] {
  const prefix = title + SEPARATOR
  const rest = title && line.startsWith(prefix) ? line.slice(prefix.length) : line.split(SEPARATOR).slice(1).join(SEPARATOR)
  return rest
    .split(SEPARATOR)
    .map(a => a.trim())
    .filter(Boolean)
}

export function channelArtists(channel: string): string[] {
  const name = stripTopic(channel).trim()
  return name ? [name] : []
}

export function parseTrackDescription(description: string, title: string, channel: string): TrackMeta {
  const lines = description.split(/\r?\n/).map(l => l.trim())
  const index = lines.findIndex(l => l.includes(SEPARATOR) && !NOT_ALBUM.test(l))
  let artists: string[] = []
  let album = ''
  if (index >= 0) {
    artists = artistsFromLine(lines[index]!, title)
    const next = lines.slice(index + 1).find(l => l.length > 0)
    if (next && !NOT_ALBUM.test(next)) album = next
  }
  return { artists: artists.length > 0 ? artists : channelArtists(channel), album }
}
