import { stripTopic } from './classify'

export const SEPARATOR = ' · '

export interface TrackMeta {
  artists: string[]
  album: string
}

const NOT_ALBUM = /^(℗|©|Released on:|Auto-generated by YouTube|Provided to YouTube by)/

function artistsFromLine(line: string, title: string): string[] {
  const prefix = title + SEPARATOR
  const rest = title && line.startsWith(prefix) ? line.slice(prefix.length) : line.split(SEPARATOR).slice(1).join(SEPARATOR)
  return rest
    .split(SEPARATOR)
    .map(a => a.trim())
    .filter(Boolean)
}

function nfc(s: string): string {
  return s.normalize('NFC')
}

function ownerFirst(artists: string[], channel: string): string[] {
  const owner = nfc(stripTopic(channel)).trim().toLowerCase()
  const index = artists.findIndex(a => a.toLowerCase() === owner)
  return index > 0 ? [artists[index]!, ...artists.slice(0, index), ...artists.slice(index + 1)] : artists
}

export function channelArtists(channel: string): string[] {
  const name = nfc(stripTopic(channel)).trim()
  return name ? [name] : []
}

export function parseTrackDescription(description: string, title: string, channel: string): TrackMeta {
  const lines = nfc(description).split(/\r?\n/).map(l => l.trim())
  const index = lines.findIndex(l => l.includes(SEPARATOR) && !NOT_ALBUM.test(l))
  let artists: string[] = []
  let album = ''
  if (index >= 0) {
    artists = ownerFirst(artistsFromLine(lines[index]!, nfc(title)), channel)
    const next = lines.slice(index + 1).find(l => l.length > 0)
    if (next && !NOT_ALBUM.test(next)) album = next
  }
  return { artists: artists.length > 0 ? artists : channelArtists(channel), album }
}
