import { describe, expect, it } from 'vitest'
import { classify } from '../src/domain/classify'
import { parseTrackDescription } from '../src/domain/parse'

const DESCRIPTION = `Provided to YouTube by Sony Music Entertainment

Группа крови · Кино · Виктор Цой

Группа крови

℗ 1988 Moroz Records

Released on: 1988-01-01

Auto-generated by YouTube.`

describe('классификация', () => {
  it('канал - Topic', () => {
    expect(classify('Кино - Topic', 'что угодно')).toBe('track')
  })

  it('автосгенерированное описание', () => {
    expect(classify('Some Label', DESCRIPTION)).toBe('track')
  })

  it('обычное видео', () => {
    expect(classify('Kino Official', 'Клип на песню')).toBe('music')
    expect(classify('Topic Channel', 'Provided to YouTube by me')).toBe('music')
    expect(classify(undefined, undefined)).toBe('music')
  })
})

describe('разбор описания автотрека', () => {
  it('исполнитель — первый после названия, альбом — следующий блок', () => {
    expect(parseTrackDescription(DESCRIPTION, 'Группа крови', 'Кино - Topic')).toEqual({ artist: 'Кино', album: 'Группа крови' })
  })

  it('название содержит разделитель', () => {
    const d = 'Provided to YouTube by X\n\nA · B · Artist · Other\n\nAlbum\n\nAuto-generated by YouTube.'
    expect(parseTrackDescription(d, 'A · B', 'Artist - Topic')).toEqual({ artist: 'Artist', album: 'Album' })
  })

  it('CRLF и лишние пробелы', () => {
    const d = 'Provided to YouTube by X\r\n\r\n  Song · Singer  \r\n\r\n\r\n  Record  \r\n\r\nAuto-generated by YouTube.'
    expect(parseTrackDescription(d, 'Song', 'Singer - Topic')).toEqual({ artist: 'Singer', album: 'Record' })
  })

  it('без альбома', () => {
    const d = 'Provided to YouTube by X\n\nSong · Singer\n\n℗ 2020 X\n\nAuto-generated by YouTube.'
    expect(parseTrackDescription(d, 'Song', 'Singer - Topic')).toEqual({ artist: 'Singer', album: '' })
  })

  it('запасной вариант — имя канала без - Topic', () => {
    expect(parseTrackDescription('', 'Song', 'Singer - Topic')).toEqual({ artist: 'Singer', album: '' })
    expect(parseTrackDescription('Provided to YouTube by X\n\nSong\n\nAuto-generated by YouTube.', 'Song', 'Singer - Topic').artist).toBe('Singer')
  })
})
